config/routes.rb
Platypus::Application.routes.draw do
  get "search/index"
  get "search/query"
  get "search/ajax"

  resources :search_items

  resources :search_lists

  match 'search' => 'search#result', as: 'search'

  root to: 'search#index', as: 'start'

end

app/models/search_item.rb
class SearchItem < ActiveRecord::Base
  belongs_to :search_list;

  before_save :ensure_unique_query

  # ensure that duplicate queries are not saved
  def ensure_unique_query
    search_list.search_items.each do |item|
      if item.query == self.query
        return false
      end
    end
    return true
  end
  
end

app/models/search_list.rb
class SearchList < ActiveRecord::Base
  has_many :search_items, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  private

    # Function that returns the search_list associated with
    # the current session
    def current_search_list
      SearchList.find(session[:search_list_id])
    rescue ActiveRecord::RecordNotFound
      list = SearchList.create
      session[:search_list_id] = list.id
      list
    end
end

app/controllers/search_controller.rb
require 'gsearch-parser'

class SearchController < ApplicationController
  def index
  end
 
  def result
    # Extract query from GET params
    query = params[:q]

    # Initalize variables to be used by the View
    @webSearch = GSearchParser.webSearch(query)
    @nextURI = @webSearch.nextURI

    # Get the current list associated with this session
    @list = current_search_list

    # Create a new search_item attached to this list from the query
    search_item = @list.search_items.build(query: query)

    # Save to database
    search_item.save
  end

  def ajax
    # Extract uri from POST param
    uri = params[:uri].strip

    # Decode the uri
    decodedURI = URI.unescape(uri).gsub(/ /, '+')

    # Parse a new search page using the uri
    @webSearch = GSearchParser.parseSearchPage(decodedURI)
    @nextURI = @webSearch.nextURI

    respond_to do |format|
      format.html { render layout: false }
    end
  end

end

app/controllers/search_items_controller.rb
class SearchItemsController < ApplicationController
  # GET /search_items
  # GET /search_items.json
  def index
    @search_items = SearchItem.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @search_items }
    end
  end

  # GET /search_items/1
  # GET /search_items/1.json
  def show
    @search_item = SearchItem.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @search_item }
    end
  end

  # GET /search_items/new
  # GET /search_items/new.json
  def new
    @search_item = SearchItem.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @search_item }
    end
  end

  # GET /search_items/1/edit
  def edit
    @search_item = SearchItem.find(params[:id])
  end

  # POST /search_items
  # POST /search_items.json
  def create
    @list = current_search_list
    @search_item = @list.search_items.build(params[:search_item])

    respond_to do |format|
      if @search_item.save
        format.html { redirect_to @search_item }
        format.json { render json: @search_item, status: :created, location: @search_item }
      else
        format.html { render action: "new" }
        format.json { render json: @search_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /search_items/1
  # PUT /search_items/1.json
  def update
    @search_item = SearchItem.find(params[:id])

    respond_to do |format|
      if @search_item.update_attributes(params[:search_item])
        format.html { redirect_to @search_item, notice: 'Search item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @search_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /search_items/1
  # DELETE /search_items/1.json
  def destroy
    @search_item = SearchItem.find(params[:id])
    @search_item.destroy

    # Get the current list associated with this session
    @search_list = current_search_list

    respond_to do |format|
      format.html { redirect_to search_items_url }
      format.json { head :no_content }
      format.js
    end
  end
end

app/controllers/search_lists_controller.rb
class SearchListsController < ApplicationController
  # GET /search_lists
  # GET /search_lists.json
  def index
    @search_lists = SearchList.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @search_lists }
    end
  end

  # GET /search_lists/1
  # GET /search_lists/1.json
  def show
    @search_list = SearchList.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @search_list }
    end
  end

  # GET /search_lists/new
  # GET /search_lists/new.json
  def new
    @search_list = SearchList.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @search_list }
    end
  end

  # GET /search_lists/1/edit
  def edit
    @search_list = SearchList.find(params[:id])
  end

  # POST /search_lists
  # POST /search_lists.json
  def create
    @search_list = SearchList.new(params[:search_list])

    respond_to do |format|
      if @search_list.save
        format.html { redirect_to @search_list, notice: 'Search list was successfully created.' }
        format.json { render json: @search_list, status: :created, location: @search_list }
      else
        format.html { render action: "new" }
        format.json { render json: @search_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /search_lists/1
  # PUT /search_lists/1.json
  def update
    @search_list = SearchList.find(params[:id])

    respond_to do |format|
      if @search_list.update_attributes(params[:search_list])
        format.html { redirect_to @search_list, notice: 'Search list was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @search_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /search_lists/1
  # DELETE /search_lists/1.json
  def destroy
    @search_list = SearchList.find(params[:id])
    @search_list.destroy

    respond_to do |format|
      format.html { redirect_to search_lists_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # helper function that determines which div tag to wrap
  # the search bar that shows up on every page with.
  def search_bar_location
    div_class = 'top-search-bar'
    if current_page?('/') 
      div_class = 'index-page-search-bar'
    end
    div_class     
  end
 
  # helper function that returns true if currently viewing the homepage
  def on_home_page
    if current_page?('/')
      return true
    end
    return false;
  end

end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/search_items_helper.rb
module SearchItemsHelper
end

app/helpers/search_lists_helper.rb
module SearchListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Web Searching, Simplified</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body class='page <%= controller.controller_name %>'>

<div id="banner">
</div>


<div class="<%= search_bar_location %>">
  <% if on_home_page %>
    <div id="logo">
       <%= image_tag("logo.png", class: "picture") %>
    </div>
  <% end %>
  <%= render 'search/search_bar' %>
</div>

<% if on_home_page %>
    <center><b>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbspHit Enter to search!</b></center>
<% end %>


<% if !on_home_page %>
  <div id="right-nav-menu-wrapper">
    <div id="right-nav-menu">
      <%= link_to "Recent Searches", @list %>
    </div>
  </div>
<% end %>

<div id="main">
  <%= yield %>
</div>

</body>
</html>

app/views/search/_result_divs.html.erb
<% @webSearch.each do |web| %>
  <div class="result-div">
    <%= image_tag("x-mark.png", class: "delete-image", style: "display:none;") %>
    <div class="content">
      <p>
        <span class="result-title"> <%= link_to web.title.html_safe, 'http://'+strip_tags(web.uri), target: "_blank" %></span><br />
        <%= web.content.html_safe %>
        <span class="result-uri"><%= link_to web.uri.html_safe, 'http://'+strip_tags(web.uri), target: "_blank"  %></span>
      </p>
    </div> 
    
    
<%= image_tag("thumbs_up.png", class: "check-image", style: "display:none;") %>
<%= image_tag("right_tab.png", class: "rtab-image", style:"display:none;") %>
<%= image_tag("visited_tab.png", class: "visit-image", style:"display:none;") %>
  </div>
<% end %>

app/views/search/_search_bar.html.erb
<div class="search-wrapper">
  <%= form_tag(search_path, :method => "get") do %>
    <%= text_field_tag :q, params[:q], class: 'text-field' %>
    
  <% end %>
</div>

app/views/search/ajax.html.erb
<%= render 'search/result_divs' %>

<div class="next-page" style="display: none;">
  <%= @nextURI %>
</div>

app/views/search/ajax.js.erb
$('.results.').html("<%=j render 'search/result_divs'  %>")

app/views/search/index.html.erb
<h1 style="text-align:center;
           position:relative;
           top:-105px;">

</h1>

app/views/search/result.html.erb
<div class="results clearfix">
  <%= render 'search/result_divs' %>
  <div class="ajax-load-wrapper">
    <%= image_tag("ajax-loader.gif", class: "ajax-load", style: "display: none;") %>
  </div>
  <div class="next-page" style="display: none;">
    <%= @nextURI %>
  </div>
</div>

app/views/search_items/_form.html.erb
<%= form_for(@search_item) do |f| %>
  <% if @search_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@search_item.errors.count, "error") %> prohibited this search_item from being saved:</h2>

      <ul>
      <% @search_item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="search-wrapper">
    <div class="centered">
      <div class="search-query">
        <%= f.text_field :query %>
      </div>
      <div class="search-button">
        <%= f.submit 'Search' %>
      </div>
      <div class="clear-div">
      </div>
    </div>
  </div>
<% end %>

app/views/search_items/destroy.js.erb
$('#recent-search-list').html("<%=j render @search_list %>");

app/views/search_items/edit.html.erb
<h1>Editing search_item</h1>

<%= render 'form' %>

<%= link_to 'Show', @search_item %> |
<%= link_to 'Back', search_items_path %>

app/views/search_items/index.html.erb
<h1>Listing search_items</h1>

<table>
  <tr>
    <th>Search list</th>
    <th>Query</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @search_items.each do |search_item| %>
  <tr>
    <td><%= search_item.search_list_id %></td>
    <td><%= search_item.query %></td>
    <td><%= link_to 'Show', search_item %></td>
    <td><%= link_to 'Edit', edit_search_item_path(search_item) %></td>
    <td><%= link_to 'Destroy', search_item, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Search item', new_search_item_path %>

app/views/search_items/new.html.erb
<%= render 'form' %>

app/views/search_items/show.html.erb
<p id="notice"><%= notice %></p>

<%= render 'form' %>

<p>
  <b>Search list:</b>
  <%= @search_item.search_list_id %>
</p>

<p>
  <b>Query:</b>
  <%= @search_item.query %>
</p>

app/views/search_lists/_form.html.erb
<%= form_for(@search_list) do |f| %>
  <% if @search_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@search_list.errors.count, "error") %> prohibited this search_list from being saved:</h2>

      <ul>
      <% @search_list.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/search_lists/_search_list.html.erb
<% search_list.search_items.reverse.each do |item| %>
  <ul>
    <li>
    <%= link_to item.query, search_path + "?q=#{item.query}", class: "search-keyword" %>
    <%= button_to '&times;'.html_safe, item, method: :delete, remote: true, form_class: 'recent-search-delete' %>
    </li>
  </ul>
<% end %>

app/views/search_lists/edit.html.erb
<h1>Editing search_list</h1>

<%= render 'form' %>

<%= link_to 'Show', @search_list %> |
<%= link_to 'Back', search_lists_path %>

app/views/search_lists/index.html.erb
<h1>Listing search_lists</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @search_lists.each do |search_list| %>
  <tr>
    <td><%= link_to 'Show', search_list %></td>
    <td><%= link_to 'Edit', edit_search_list_path(search_list) %></td>
    <td><%= link_to 'Destroy', search_list, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Search list', new_search_list_path %>

app/views/search_lists/new.html.erb
<h1>New search_list</h1>

<%= render 'form' %>

<%= link_to 'Back', search_lists_path %>

app/views/search_lists/show.html.erb
<p id="notice"><%= notice %></p>

<div class="middle-content clearfix">
  <h2>Recent search terms</h2>
  <div id="recent-search-list">
    <%= render @search_list %>
  </div>
</div>